### ISSUE TITLE
How to use Github connector with special char team names?

### ISSUE THREAD

**Issue by jthorupp** [dexidp/website#162]
Hello!
I'm new to this and just faced an issue with usage of `&` in a team display name in github.
According to the [github connector docs](https://github.com/dexidp/website/blob/main/content/docs/connectors/github.md#github-enterprise) the `orgs` config should look like something this:
```yaml
orgs:
- name: organisation-name
  teams:
      - red
      - blue
```
Let's say that a re-organisation happens in the enterprise and we need to merge Red and Blue teams. A new github team is created called `Red & Blue`. All the codeowner files and similar are updated to `path/to/code/** @organisation-name/red-blue` and everything validates in PRs etc., but in the dex config it can't resolve the group name using the following config:
```yaml
orgs:
- name: organisation-name
  teams:
      - red-blue
```

What's the correct config for these situations?

Thanks!
